```{r}
pacman::p_load(
  "tidyverse",
  "openmeteo",
  "ggtext",
  "r2country"
)


```
```{r}
theme_set(theme_minimal())
theme_update(
    panel.grid.minor = element_line(size = 0.25),
    panel.grid.major = element_line(size = 0.75),
    plot.title = element_text(face = "bold", size = 22),
    plot.subtitle = element_text(size = 16),
    text = element_text(color = "#5d524b", family = "Segoe UI", size = 18),
    panel.background = element_rect(fill = '#fff9f5', color = '#fff9f5'),
    plot.background = element_rect(fill = '#fff9f5', color = '#fff9f5'),
    panel.grid = element_line(color = "#f3ede9"),
    axis.text.x = element_text(angle = 90, color = "#9b928c"),
    axis.title = element_text(face = "bold", size = 15),
    axis.title.y = element_text(vjust = +2),
    axis.title.x = element_text(vjust = -0.75)
)
```
```{r}
dfCCC <- r2country::capitalOf |> as.data.frame() |>
  pivot_longer(cols = everything(), names_to = "country", values_to = "city") |>
  filter(
    country %in% (
      r2country::continentOf |>
      as.data.frame() |>
      pivot_longer(cols = everything(), names_to = "country", values_to = "continent") |>
      filter(continent == "Europe") |>
      pull("country")
    )
  )

dfCCC <- dfCCC |>
  filter(
    !(country %in% c(
      "faeroe.islands", "belarus", "andorra", "san.marino", "montenegro",
      "isle.of.man", "liechtenstein", "luxembourg", "gibraltar"
    ))
  )
```


```{r}
dfWeatherEU <- 
  lapply(dfCCC$city ,function(city) {
    location <- try(openmeteo::geocode("ASDDSA")$name)
    if (class(location) == "try-error") return(NA)
    df <- 
      openmeteo::weather_history(
        location = location,
        start = "1970-01-01",
        end = "2023-12-31",
        hourly = "temperature_2m"
      )
    df$city <- location
    df$country <- pull(dfCCC |> filter(city == location), "country")[1]
  }) |> do.call(rbind, args = _)


if (!file.exists("2024-06-20/dfWeatherEU.csv")) {
  dfWeatherEU <-
    dfCCC$city |>
    map_df(~getCityData(.))

  write_csv(dfWeatherEU, "2024-06-20/dfWeatherEU.csv")
}

lapply(1:4, function(x) {
  if (x == 1) return(NA)
  return(iris)
}) |> do.call(rbind, args = _)

```


```{r}
s <- svglite::svgstring(width = 24, height = 6, scaling = 1)
dfWeather |>
  mutate(
    d = day(datetime),
    w = week(datetime),
    m = month(datetime),
    y = year(datetime)
  ) |>
  group_by(y, m) |>
  summarise(temp = round(mean(hourly_temperature_2m, na.rm = T), 1)) |>
  ungroup() |> group_by(m) |>
  mutate(
    avg = temp - mean(temp),
    status = if_else(avg >= 0, "hotter", "colder")
  ) |>
  na.omit() |>
  ggplot(aes(
    y = factor(m),
    x = y
  )) +
  geom_tile(aes(fill = status)) +
  geom_text(aes(
    label = round(avg, 1)
  ), color = "white") +
  scale_fill_manual(values = c("#82a6bd", "#F57251")) +
  scale_x_continuous(
    breaks = seq(1970, 2023, 1),
    expand = c(0, 0)
  ) +
  labs(
    y = "month",
    x = "year",
    fill = "",
    title = "Average Temperature Deviation",
    caption =  paste0("Open-Meteo\n", "hourly temp2m\n", Sys.Date(), "\n MK"),
    subtitle = glue::glue(
      "
      <span style = 'color: #5d524b; font-size: 17px'><b>▶</b></span> Deviation from the average (1970-2023) temperature in a given month<br> 
      <span style = 'color: #5d524b; font-size: 17px;'><b>▶</b></span> Temperature measured 2 meters over the ground in Wroclav (Poland)
      "
    )
  ) +
  theme(
    plot.subtitle = element_markdown(),
    legend.position = "top",
    legend.text = element_text(size = 14, face = "bold")
  )
  
htmltools::HTML(s())
invisible(dev.off())
htmltools::save_html(htmltools::HTML(s()), "wroclav_temp.html")
```

```{r}

```

