
```{r}
source("../main.R")
```

```{r}
dfCCC <- r2country::capitalOf |> as.data.frame() |>
  pivot_longer(cols = everything(), names_to = "country", values_to = "city") |>
  filter(
    country %in% (
      r2country::continentOf |>
      as.data.frame() |>
      pivot_longer(cols = everything(), names_to = "country", values_to = "continent") |>
      filter(continent == "Europe") |>
      pull("country")
    )
  )

dfCCC <- dfCCC |>
  filter(
    !(country %in% c(
      "faeroe.islands", "belarus", "andorra", "san.marino", "montenegro",
      "isle.of.man", "liechtenstein", "luxembourg", "gibraltar"
    ))
  )
```


```{r}

if (!file.exists("dfWeatherEU.csv")) {
  dfWeatherEU <- 
  lapply(dfCCC$city, function(city) {
    # Get city location, if not found then NA
    location <- try(openmeteo::geocode(city)$name)
    if (class(location)[1] == "try-error") return(NA)
    
    # Get data, if not found then NA
    df <- try(openmeteo::weather_history(
      location = location,
      start = "1970-01-01",
      end = "2023-12-31",
      hourly = "temperature_2m"
    ))
    if (class(df)[1] == "try-error") return(NA)
    
    # Add city & country to dataframe
    df$city <- location
    df$country <- dplyr::pull(dplyr::filter(dfCCC, city == location), "country")[1]
    return(df)
  }) |>
  # bind the returned list
  do.call(rbind, args = _) |> as_tibble()
  
  write_csv(dfWeatherEU, "dfWeatherEU.csv")
} else {
  dfWeatherEU <- 
    read_csv("dfWeatherEU.csv")
}

```


```{r}
dfWeatherEU5 <- 
  dfWeatherEU |>
  filter(between(year(datetime), 1970, 2023)) |>
  mutate(
    d = day(datetime),
    w = week(datetime),
    m = month(datetime),
    y = year(datetime)
  ) 
  
```



```{r}
monthsFactor <- c(
  "Jan" = 1,
  "Feb" = 2,
  "Mar" = 3,
  "Apr" = 4,
  "May" = 5,
  "Jun" = 6,
  "Jul" = 7,
  "Aug" = 8,
  "Sep" = 9,
  "Oct" = 10,
  "Nov" = 11,
  "Dec" = 12
)

(
  p1 <- dfWeatherEU5 |>
  group_by(y, m) |>
  summarise(avg = round(mean(hourly_temperature_2m, na.rm = T), 1)) |>
  ungroup() |> group_by(m) |>
  mutate(
    avgDiff = avg - mean(avg),
    status = case_when(
      avgDiff >= 0 ~ "#c8102e",
      T ~ "#408ac2"
    )
  ) |>
  na.omit() |>
  ggplot(aes(
    y = factor(m, labels = names(monthsFactor), ordered = T),
    x = y
  )) +
  geom_tile(aes(fill = status, colors = status), show.legend = F) +
  geom_text(aes(
    label = round(avgDiff, 1)
  ), color = "white", show.legend = F) +
  scale_x_continuous(
    breaks = seq(1970, 2023, 5),
    expand = c(0, 0)
  ) +
  scale_fill_identity() +
  theme(
    plot.subtitle = element_markdown(),
    legend.position = "top",
    legend.text = element_text(size = 14, face = "bold")
  ) +
  labs(
    x = "",
    y = ""
  )  
)
```


```{r}
(
  p2 <- dfWeatherEU5 |>
  group_by(y) |>
  summarise(avg = round(mean(hourly_temperature_2m, na.rm = T), 1)) |>
  ungroup() |>
  mutate(
    avgDiff = avg - mean(avg, na.rm = T),
    status = if_else(avgDiff >= 0, "hotter", "colder")
  ) |>
  ggplot(aes(
    y = avgDiff,
    x = y
  )) +
  geom_col(aes(fill = status), show.legend = F) +
  geom_text(aes(
    label = round(avgDiff, 1),
    y = .15 * (avgDiff / abs(avgDiff)) + avgDiff,
    color = status
  ), show.legend = F) +
  scale_x_continuous(
    breaks = seq(1970, 2023, 5),
    expand = c(0, 0)
  ) +
  scale_fill_manual(values = c("#408ac2", "#c8102e")) +
  scale_color_manual(values = c("#408ac2", "#c8102e")) +
  theme(
    subtitle = element_markdown(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    plot.subtitle = element_markdown(),
    legend.position = "top",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.text = element_text(size = 14, face = "bold")
  ) + labs(
    x = "", y = "",
    title = "Deviation from the avg. temperature",
    subtitle = "measured 2m above the ground in capitols of 35 EU countries since 1970"
  ) 
)
```

```{r}
(
  p3 <-
  dfWeatherEU5 |>
  group_by(m, y) |>
  summarise(avg = round(mean(hourly_temperature_2m, na.rm = T), 3)) |>
  group_by(m) |>
  summarise(
    avg = mean(avg, na.rm = T),
    status = if_else(avg >= 0, "hotter", "colder")
  ) |>
  ggplot(aes(
    x = avg,
    y = factor(m)
  )) +
  geom_col(aes(fill = status), show.legend = F) +
  geom_text(aes(
    label = round(avg, 2),
    color = status
  ), show.legend = F, nudge_x = 1) +
  scale_fill_manual(values = c("#acacac")) +
  scale_color_manual(values = c("#515151")) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    plot.subtitle = element_markdown(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.text = element_text(size = 14, face = "bold")
  ) + labs(
    x = "", y = "",
    subtitle = "average tmeperature in a given month",
    caption =  paste0("Open Meteo Data\n", "temperature_2m\n", Sys.Date(), "\n MK")
  ) 
)
```

```{r}
layout <- "
AAAA#
CCCCB
"

(
  p2 + 
  p3 +
  p1 +
  plot_layout(design = layout) 
) |>
asSVG(32, 13, scaling = 1.5, save = T, name = "AvgTempEU.html")
```

```{r}
dfWeatherEUYoY <- 
  dfWeatherEU |>
  group_by(y) |>
  summarise(avg = mean(hourly_temperature_2m)) |>
  mutate(
    date = as.Date(paste(y, 1, 1, sep = "-"), format = "%Y-%m-%d"),
    bavg = lag(avg),
    YoY = avg/bavg,   
    status = if_else((avg - bavg) < 0, "colder", "warmer"),
    max = if_else(avg >= bavg, avg, bavg)
  )

model <- lm(avg ~ y, data = dfWeatherEUYoY)$coefficients 


(
 dfWeatherEUYoY |>
    ggplot(aes(
      x = y,
      y = avg
    )) +
    stat_smooth(se = F, method = "lm", color = "#1f1f1f", ) +
    geom_segment(aes(
      xend = y,
      yend = bavg,
      color = (status),
      group = 1
    ), linewidth = 5, show.legend = F) +
    scale_color_manual(values = c("colder" = "#408ac2", "warmer" = "#c8102e")) +
    geom_text(aes(
      y = max,
      label = paste0(round(YoY * 100, 0) - 100, "%")
    ), nudge_y = .1) +
    scale_y_continuous(
      breaks = seq(10, 12, 1),
      minor_breaks = seq(9.5, 12.5, .1)
    ) + 
    annotate(geom = "text", x = 2020, y = 11, label = paste0("Avg. temp. growth each 25y: ", round(model[2] * 25, 2), "°C"), size = 5) +
    labs(
      x = "Year",
      y = "Average temperature (°C)", 
      title = "Change of average temperature in Europe",
      subtitle = glue::glue(
          "
          <span style = 'color: #5d524b; font-size: 14px;'><b>▶</b></span> between 1970 & 2023 <br>
          <span style = 'color: #408ac2; font-size: 24px;'><b>colder</b></span> 
          <span style = 'color: #c8102e; font-size: 24px;'><b>warmer</b></span>
          "
        ),
      caption =  paste0("Open Meteo Data\n", "temperature_2m\n", Sys.Date(), "\n MK")
    ) +
    theme(
      plot.subtitle = element_markdown()
    )
) |>
  asSVG(18, 6, save = T, name = "AvgTempEUchange.html")
  
  
```

